### ISSUE TITLE
ChatGPT模块输入的文本过多时，无发送按钮以及无法移动到最后一行

### ISSUE THREAD

**Issue by QsSama-W** [rnchg/Apt#19]
您好，GPT模块遇到个BUG，当输入的文本过多的时候，发送按钮会被UI的自动排列移到屏幕外面去，而且没有任何办法在输入框内滑动代码至于最后一行，这个GPT模块 对话框UI部分的BUG方便抽空修复一下嘛？
![Uploading 6d7ced81156e93338c009fa8f8da3c1012196972.png…]()

**Comment by rnchg** [comment]
新版本中已修复
