### ISSUE TITLE
GPT 重复回复

### ISSUE THREAD

**Issue by poguanzi** [rnchg/Apt#3]
提问：你是基于 GPT 3.5 版本的吗？

Chatbox 回复：

>  不，我不是基于 GPT-3.5 版本。我是一个基于 GPT-3 的人工智能模型，由 OpenAI 开发出来，但我的知识截止日期是2023年，所以我不能提䇏最新的信息。
support>
我是基于 GPT-3 一个人工智能模型，由 OpenAI 开发出来。

support>
我是基于 GPT-3 一个人工智能，由 OpenAI 开发出来，以模仿人类的对话和互动。GPT-3 是一个基于深度学习的语言模型，可以理解和生成文本，并根据给定的指导完成任务。它通过训练过程，学习了大量的文本数据，以便在多种任务上提供有效的回答和解答。

response>
我是基于 GPT-3 一个人工智能，由 OpenAI 开发出来，以模仿人类的对话和互动。GPT-3 是一个基于深度学习的语言模型，可以理解和生成文本，并根据给定的指导完成任务。它通过训练过程，学习了大量的文本数据，以便在多种任务上提供有效的回答和解答。

![微信截图_20240703112020](https://github.com/rnchg/Apt/assets/22453534/3d43b0aa-3d6a-496c-855a-def91a78e93e)

**Comment by rnchg** [comment]
谢谢，正在进行模型微调，预计一周之内会发布版本修复
